services:
  # Drand service for node 1
  drand-1:
    container_name: drand-1
    hostname: drand-1
    image: drand:latest
    entrypoint: /go/drand/scripts/./drand-1.sh
    volumes:
      - ./drand/start_scripts/:/go/drand/scripts/
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.21

  # Drand service for node 2
  drand-2:
    container_name: drand-2
    hostname: drand-2
    image: drand:latest
    entrypoint: /go/drand/scripts/./drand-2.sh
    volumes:
      - ./drand/start_scripts/:/go/drand/scripts/
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.22

  # Drand service for node 3
  drand-3:
    container_name: drand-3
    hostname: drand-3
    image: drand:latest
    entrypoint: /go/drand/scripts/./drand-3.sh
    volumes:
      - ./drand/start_scripts/:/go/drand/scripts/
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.23

  #Lotus node service
  lotus:
    image: lotus:latest
    container_name: lotus
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.24
    volumes:
      - ./data/lotus:${LOTUS_DATA_DIR}
      - ./lotus/start_scripts/lotus-node.sh:${LOTUS_DATA_DIR}/lotus-node.sh
    environment:
      - LOTUS_SHARK_HEIGHT=${SHARK_HEIGHT}
      - LOTUS_HYGGE_HEIGHT=${HYGGE_HEIGHT}
      - LOTUS_LIGHTNING_HEIGHT=${LIGHTNING_HEIGHT}
      - LOTUS_THUNDER_HEIGHT=${THUNDER_HEIGHT}
      - LOTUS_WATERMELON_HEIGHT=${WATERMELON_HEIGHT}
      - LOTUS_DRAGON_HEIGHT=${DRAGON_HEIGHT}
      - LOTUS_GENESIS_NETWORK_VERSION=${GENESIS_NETWORK_VERSION}
      - LOTUS_WAFFLE_HEIGHT=${WAFFLE_HEIGHT}
    env_file:
      - .env
      - ./lotus/lotus.env
    entrypoint: ["${LOTUS_DATA_DIR}/lotus-node.sh"]

  # Lotus miner service
  lotus_miner:
    image: lotus:latest
    container_name: lotus-miner
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.25
    volumes:
      - ./data/lotus:${LOTUS_DATA_DIR}
      - ./lotus/start_scripts/lotus-miner.sh:${LOTUS_DATA_DIR}/lotus-miner.sh
    environment:
      - LOTUS_SHARK_HEIGHT=${SHARK_HEIGHT}
      - LOTUS_HYGGE_HEIGHT=${HYGGE_HEIGHT}
      - LOTUS_LIGHTNING_HEIGHT=${LIGHTNING_HEIGHT}
      - LOTUS_THUNDER_HEIGHT=${THUNDER_HEIGHT}
      - LOTUS_WATERMELON_HEIGHT=${WATERMELON_HEIGHT}
      - LOTUS_DRAGON_HEIGHT=${DRAGON_HEIGHT}
      - LOTUS_GENESIS_NETWORK_VERSION=${GENESIS_NETWORK_VERSION}
      - LOTUS_WAFFLE_HEIGHT=${WAFFLE_HEIGHT}
    env_file:
      - ./lotus/lotus-miner.env
      - .env
    ports:
      - 2345:2345
    entrypoint: ["${LOTUS_DATA_DIR}/lotus-miner.sh"]
   

  # Forest service
  forest:
    image: forest:latest
    container_name: forest
    volumes:
      - ./data/lotus:${LOTUS_DATA_DIR}
      - ./data/forest:${FOREST_DATA_DIR}
      - ./forest/forest_config.toml.tpl:/forest/forest_config.toml.tpl
      - ./forest/start_scripts/forest-init.sh:${FOREST_DATA_DIR}/forest-init.sh
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.26
    environment:
      - RUST_LOG=info,forest_filecoin::blocks::header=trace
      - FOREST_GENESIS_NETWORK_VERSION=${GENESIS_NETWORK_VERSION}
      - FOREST_SHARK_HEIGHT=${SHARK_HEIGHT}
      - FOREST_HYGGE_HEIGHT=${HYGGE_HEIGHT}
      - FOREST_LIGHTNING_HEIGHT=${LIGHTNING_HEIGHT}
      - FOREST_THUNDER_HEIGHT=${THUNDER_HEIGHT}
      - FOREST_WATERMELON_HEIGHT=${WATERMELON_HEIGHT}
      - FOREST_DRAGON_HEIGHT=${DRAGON_HEIGHT}
      - FOREST_WAFFLE_HEIGHT=${WAFFLE_HEIGHT}
    env_file:
      - .env      
      - ./forest/forest.env
    entrypoint: ["${FOREST_DATA_DIR}/forest-init.sh"]

  # Forest <-> Lotus connector service
  forest-connecter:
    image: forest:latest
    container_name: forest-connector
    volumes:
      - ./data/lotus:${LOTUS_DATA_DIR}
      - ./data/forest:${FOREST_DATA_DIR}
      - ./forest/start_scripts/forest-connector.sh:${FOREST_DATA_DIR}/forest-connector.sh
    env_file:
      - .env
      - ./forest/forest.env
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.27
    entrypoint: [ "${FOREST_DATA_DIR}/forest-connector.sh" ]


networks:
  antithesis-net:
    ipam:
      config:
        - subnet: 10.20.20.0/24
