services:
  drand-1:
    container_name: drand-1
    hostname: drand-1
    image: drand:latest
    entrypoint: /go/drand/scripts/./drand-1.sh
    volumes:
      - ./drand/start_scripts/:/go/drand/scripts/
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.21

  drand-2:
    container_name: drand-2
    hostname: drand-2
    image: drand:latest
    entrypoint: /go/drand/scripts/./drand-2.sh
    volumes:
      - ./drand/start_scripts/:/go/drand/scripts/
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.22

  drand-3:
    container_name: drand-3
    hostname: drand-3
    image: drand:latest
    entrypoint: /go/drand/scripts/./drand-3.sh
    volumes:
      - ./drand/start_scripts/:/go/drand/scripts/
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.23

  lotus-1:
    container_name: lotus-1
    hostname: lotus-1
    image: "lotus:latest"
    healthcheck:
      test: >-
        curl -s -x post -h "content-type: application/json"
        --data '{ "jsonrpc": "2.0", "method": "filecoin.chainhead", "params": [], "id": 1 }'
        http://lotus-1:1234/rpc/v0 || exit 1
      interval: 10s
      retries: 10
      timeout: 5s
    depends_on:
      - drand-1
    environment:
      LOTUS: lotus-1
      LOTUS_COUNT: 2
      LOTUS_PATH: /root/.lotus
      LOTUS_MINER_PATH: /root/.lotus-miner
      LOTUS_SKIP_GENESIS_CHECK: _yes_
      CGO_CFLAGS_ALLOW: -D__BLST_PORTABLE__
      CGO_CFLAGS: -D__BLST_PORTABLE__
      LOTUS_FEVM_ENABLEETHRPC: true
    entrypoint: /opt/lotus_transformed/customer/entrypoint.sh
    volumes:
      - ./lotus/start_scripts/lotus-leader.sh:/opt/lotus_transformed/customer/entrypoint.sh
      - ./lotus/shared/:/opt/lotus_transformed/customer/shared/
      - ./lotus/devgen/:/opt/lotus_transformed/customer/devgen/
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.24

  forest-node:
    container_name: forest-node
    hostname: forest-node
    image: "forest:latest"
    depends_on:
      lotus-1:
        condition: service_healthy
    entrypoint: /opt/forest/start_scripts/forest-init.sh
    volumes:
      - ./lotus/shared/:/opt/forest/start_scripts/shared/
      - ./forest/start_scripts/:/opt/forest/start_scripts/
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.25

  ubuntu-playbox:
    container_name: ubuntu-playbox
    hostname: ubuntu-playbox
    image: "ubuntu:latest"
    command: ["sleep", "infinity"]
    tty: true
    stdin_open: true
    volumes:
      - ./lotus/shared/:/opt/shared/
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.26

networks:
  antithesis-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.20.0/24

